version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
      - PHOENIX_CLIENT_HEADERS=api_key=${PHOENIX_API_KEY}
      - PHOENIX_COLLECTOR_ENDPOINT=https://app.phoenix.arize.com/
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - trip-planner

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    networks:
      - trip-planner

networks:
  trip-planner:
    driver: bridge
